### ISSUE TITLE
System.ValueTuple 4.5.0 doesn't load on netcoreapp2.0

### ISSUE THREAD

**Issue by NightOwl888** [sillsdev/icu-dotnet#118]
## Describe the bug

As the title says, the [`System.ValueTuple` library version 4.5.0](https://www.nuget.org/packages/System.ValueTuple/) is not compatible with .NET Core 2.0. It is only compatible with .NET Core 2.1 and above. 

## To Reproduce

1. Create a .NET Core project targeting 2.0 (netcoreapp2.0)
2. Add a reference to icu.net NuGet package 2.5.4
3. Attempt to utilize any of the functionality (we are using RuleBasedBreakIterator, but I don't think it matters)
4. You will get an error similar to the following:

Result StackTrace:	
at Lucene.Net.Analysis.Th.TestThaiAnalyzer.SetUp() in F:\Projects\lucenenet\src\Lucene.Net.Tests.Analysis.Common\Analysis\Th\TestThaiAnalyzer.cs:line 40
--FileNotFoundException
   at Icu.NativeMethods.GetString(Func`3 lambda, Boolean isUnicodeString, Int32 initialLength)
   at Icu.Locale..ctor(String localeId)
   at Lucene.Net.Support.IcuBreakIterator..ctor(UBreakIteratorType type, CultureInfo locale) in F:\Projects\lucenenet\src\dotnet\Lucene.Net.ICU\Support\IcuBreakIterator.cs:line 64
   at Lucene.Net.Analysis.Th.ThaiTokenizer..cctor() in F:\Projects\lucenenet\src\Lucene.Net.Analysis.Common\Analysis\Th\ThaiTokenizer.cs:line 49
Result Message:	
System.TypeInitializationException : The type initializer for 'Lucene.Net.Analysis.Th.ThaiTokenizer' threw an exception.
  ----> System.IO.FileNotFoundException : Could not load file or assembly 'System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

## Expected behavior

The package should not just compile, but also load. 

## Environment

- OS:  Windows 10
- Exact version of icu.net: 2.5.4
- .NET Framework/Core version: .NET Core 2.0

## Additional context

Note that there are only 2 ways to fix this:

1. Target .NET Core 2.1 on the consuming project
2. Downgrade `System.ValueTuple` to 4.3.0, as [described on StackOverflow](https://stackoverflow.com/a/50636962/181087) (see the comments at the bottom)

We would appreciate a stable patch of 59.1.15 ASAP

**Comment by ermshiperete** [comment]
Closing this issue since .NET Core 2.0 is no longer supported by Microsoft.
