### ISSUE TITLE
ICU crash on sorting when one codepoint is missing in collation

### ISSUE THREAD

**Issue by KenZook** [sillsdev/icu-dotnet#130]
## Describe the bug
In Flex 9.0.8 (LT-20194) YurutiT project, Flex will crash when clicking the Choose Texts button. I discovered it was comparing "Yurutí Example Sentences" and "YURUTI KINSHIP TERMS" when it failed. The last i in the first word is NFD 69 301. This particular code point was not in the original collation rule

& i < ĩ <<< Ĩ << ĩ́ <<< Ĩ́

So I added it

& i < ĩ <<< Ĩ << í << ĩ́ <<< Ĩ́

and then the crash went away. So apparently ICU has some problem with this particular code point when it is not defined in the collation causing a crash. We are using an old ICU version. Perhaps the latest version would not have this crash. I would like to see us using a current version of ICU in Flex.

## To Reproduce

1. Restore Yuruti
2. Go to Texts and Words
3. Click the Choose Texts button in toolbar.
It crashes with a windows error. Event viewer has:
Application: FieldWorks.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
at Icu.NativeMethods.ucol_strcoll(SafeRuleBasedCollatorHandle, System.String, Int32, System.String, Int32)
at Icu.Collation.RuleBasedCollator.Compare(System.String, System.String)
at SIL.WritingSystems.IcuRulesCollator.Compare(System.String, System.String)
at System.Collections.Generic.ArraySortHelper`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InsertionSort(System._Canon[], Int32, Int32, System.Collections.Generic.IComparer`1<System._Canon>)
at System.Collections.Generic.ArraySortHelper`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].IntroSort(System._Canon[], Int32, Int32, Int32, System.Collections.Generic.IComparer`1<System._Canon>)
at System.Collections.Generic.ArraySortHelper`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].IntroSort(System._Canon[], Int32, Int32, Int32, System.Collections.Generic.IComparer`1<System._Canon>)
at System.Collections.Generic.ArraySortHelper`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].IntrospectiveSort(System._Canon[], Int32, Int32, System.Collections.Generic.IComparer`1<System._Canon>)
at System.Collections.Generic.ArraySortHelper`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Sort(System._Canon[], Int32, Int32, System.Collections.Generic.IComparer`1<System._Canon>)
at System.Array.Sort[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System._Canon[], Int32, Int32, System.Collections.Generic.IComparer`1<System._Canon>)
at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Sort(System.Comparison`1<System.__Canon>)
at SIL.FieldWorks.IText.TextsTriStateTreeView.LoadTextsByGenreAndWithoutGenre()
at SIL.FieldWorks.IText.TextsTriStateTreeView.LoadGeneralTexts()

(Ideally push a minimal solution that demonstrates the problem to https://gist.github.com)
Download YurutiT.zip from LT-20194.
## Expected behavior

It should bring up the Choose Texts dialog

## Screenshots

![image](https://user-images.githubusercontent.com/2299804/81864274-04d20e80-9532-11ea-862e-7a58b654e680.png)

I was able to catch it in dnSpy 6.1.4.
![image](https://user-images.githubusercontent.com/2299804/81864059-b290ed80-9531-11ea-8c24-62e51ca7bf02.png)

![image](https://user-images.githubusercontent.com/2299804/81864096-bde41900-9531-11ea-9ca0-bfbd3e420f10.png)

## Environment

- OS: Windows 8.1
- Exact version of icu.net 2.5.4+Branch.master.Sha.aa2e04611b4...
- .NET Framework/Core version ??

## Additional context

This is very tricky to get it to fail. Sometimes it works, but usually not.

**Comment by imnasnainaec** [comment]
Fix analysis by Claude Opus:

**Problem.** `RuleBasedCollator.Compare` crashes with `System.AccessViolationException` inside native `ucol_strcoll` when input contains an NFD sequence (U+0069 U+0301 = `i` + combining acute) not covered by the collation rules. Reporter is on an old ICU; adding the codepoint to the rules avoids it.

**Findings.** `Compare` and `GetSortKey` call `ucol_strcoll` / `ucol_getSortKey` directly with **no** post-call error checking (these ICU functions have no error-code out-param). The crash is a native access violation inside an old ICU — a corrupted-state exception that managed `try/catch` cannot catch by default on modern .NET. **The true fix is a sufficiently modern native ICU**; the wrapper can only mitigate.

**Fix (option A — auto-normalize gated on `NormalizationMode`).** Add a private `NormalizeIfNeeded` helper that NFC-normalizes a string, and call it inside the existing `Compare`/`GetSortKey` whenever the collator's `NormalizationMode` is not `On` (when `On`, ICU already normalizes, so skip to avoid double work). `GetSortKey` normalizes only the value sent to the native call; `SortKey.OriginalString` keeps the caller's original string. Protects *all* callers with no code change on their side.

- **Size:** S
- **Breaking:** Behavior change — under `NormalizationMode.Off`, canonically-equivalent-but-reordered combining-mark input now compares equal where it previously could differ.
- **Trade-off:** No opt-in needed and every caller is protected, but it silently changes results for `Off` callers who relied on the old ordering.

**Fix (option B — opt-in normalization via overloads, building on A).** Instead of applying A's `NormalizeIfNeeded` unconditionally, expose it behind a flag: add `Compare(string, string, bool normalizeInput)` and `GetSortKey(string, bool normalizeInput)` overloads that call the helper only when `normalizeInput` is `true`. The existing `Compare(string, string)` / `GetSortKey(string)` overrides delegate with `normalizeInput: false`, so **default behavior is unchanged — no breaking change**.

- **Size:** S (A plus the overload layer)
- **Breaking:** No
- **Trade-off:** Opt-in, so callers must pass `normalizeInput: true` to get protection — the default path can still crash on a buggy old ICU.

**Shared with both options:**
- **One-time `Debug.WriteLine` warning** when the loaded native ICU is older than a `RecommendedMinIcuVersionForCollation` constant (≈ 53, the "collation v2" rewrite; a conservative threshold since the issue names no exact fix version). Emit from the rules constructor and the static `Create` locale path, matching the existing `BreakEnumerator` `Debug.WriteLine` pattern; no public API surface change.
- Recommended complement: document the ICU version requirement in the README.
- Not pursued: `[HandleProcessCorruptedStateExceptions]` — only works on .NET Framework, ignored on .NET 5+, doesn't fix the underlying corruption.

- **Files:** `Collation/RuleBasedCollator.cs`; tests in `icu.net.tests/Collation/RuleBasedCollatorTests.cs`
- **Caveat (both options):** the `53` threshold is a defensible estimate, not a pinned fix version; adjust if a precise one is found.

**Comment by imnasnainaec** [comment]
**Downstream impact of Fix A across sillsdev**

Three repos sit on the changed path: **libpalaso** (`IcuRulesCollator` → every LDML rules-based writing system), **liblcm** (`TsStringComparer`, `MorphServices`, `StringSearcher`, homograph ordering), and **FieldWorks** (`RecordSorter`, `ManagedLgIcuCollator`, `SandboxBase.DefaultMorph`, `TextsTriStateTreeView` — the crash site here). WeSay inherits it via libpalaso; LfMerge and FwLite via liblcm.

No sillsdev code sets `NormalizationMode`, and a default `RuleBasedCollator` resolves to `Off`, so Fix A's normalize branch would be active for essentially all of them.

Measured on ICU 62 over 30,000 NFD words (LCM stores text NFD):

- sort: 31 ms → 367 ms (**11.7x**), ordering identical
- linear scan (`DefaultMorph`-style): 1.7 ms → 24.7 ms (**14.3x**), same matches
- 30k `GetSortKey`: no cost, **0 of 30,000 keys changed**

Ordering only moved for non-FCD input (marks out of canonical order), which LCM's NFD normalization prevents. And the ICU-version warning would never fire: FieldWorks/liblcm ship ICU 70, the oldest collation consumer (WeSay) ships 54 — all above the proposed threshold of 53.

So Fix A buys these projects no crash protection at a 12–15x cost on the `Compare` path. Option B, or normalizing once at libpalaso's boundary, avoids that.

**Comment by imnasnainaec** [comment]
So far, not reproducible.

Using the real Yurutí tailoring from SLDR's `yui.xml` with `í <<< Í` removed from the I line (the rules as they were when this was filed), the pair above does not crash on ICU 44, 48, 52, 54, 56–63 or 67, on Linux or on Windows (including 32-bit .NET Framework). FLEx 9.0.8 pinned ICU 54, so this was already past the ICU 53 collation rewrite.

The intermittency ("sometimes it works, but usually not") would fit a buffer over-read. `Compare` hands ICU an explicit length along with the string's own buffer, so a read past that length lands in adjacent heap and faults only when the next page happens to be unmapped. To force the issue, I put each string flush against an unmapped guard page, so any such read faults immediately. None did, on any version. Sharing one collator across 8 threads was clean too.

FieldWorks' custom ICU build doesn't account for it either: the patches touch only `source/common` (character properties and case mapping) and nothing in `source/i18n`, and the custom data adds only `nfc_fw.nrm`/`nfkc_fw.nrm`, so collation resources come from the stock `icudt`; all 263 property and 15 combining-class overrides are PUA code points, which Yurutí text doesn't use.

SLDR's `sldr/y/yui.xml` has carried `&I << í <<< Í << ĩ <<< Ĩ << ĩ́ <<< Ĩ́` since it was added in silnrsi/sldr@db3d343 (2021-05-25), and that line is unchanged as of c188a4d (2026-05-05); the rules that crashed came from the project's own writing system, not from SLDR. To be clear, that is not a fault in the rules: omitting a tailoring for `í` is valid ICU and simply leaves it at its root weight, and rules ICU cannot parse already surface as an exception rather than a crash.

**Comment by imnasnainaec** [comment]
Likely caused by #237.
