### ISSUE TITLE
AccessViolationException from BreakIterator

### ISSUE THREAD

**Issue by NightOwl888** [sillsdev/icu-dotnet#56]
We are getting an intermittent AccessViolationException when using BreakIterator in a concurrent test. This issue has been a particular thorn because on .NET Core it causes the NUnit test runner to fatally crash. 

The exception only happens in the case where:

1. There is an open FileStream being used to read a file.
2. The scenario is being run as an NUnit test, xunit seems to work fine and so does a console application.
3. There is more than one thread calling `BreakIterator.GetWordBoundaries` or `BreakIterator.GetBoundaries` at the same time.
4. Some particular strings are being used when calling `BreakIterator`.

It is a bit suspicious that it only happens when running under NUnit, but the stack trace seems to start inside of `Icu.NativeMethods.ubrk_next(IntPtr bi)`.

```
[10/22/2017 9:23:22 PM Warning] System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Icu.NativeMethods.ubrk_next(IntPtr bi) in d:\JenkinsSlaveHome\slave2\workspace\icu-dotnet_master-XUIQATPXJBEMAPQAXECBOMRZFIJEQ5ACEARUZRESUNQWYLGLR56Q\source\icu.net\NativeMethods.cs:line 1732
   at Icu.RuleBasedBreakIterator.SetText(String text) in d:\JenkinsSlaveHome\slave2\workspace\icu-dotnet_master-XUIQATPXJBEMAPQAXECBOMRZFIJEQ5ACEARUZRESUNQWYLGLR56Q\source\icu.net\RuleBasedBreakIterator.cs:line 377
   at Icu.BreakIterator.GetBoundaries(UBreakIteratorType type, Locale locale, String text, Boolean includeSpacesAndPunctuation) in d:\JenkinsSlaveHome\slave2\workspace\icu-dotnet_master-XUIQATPXJBEMAPQAXECBOMRZFIJEQ5ACEARUZRESUNQWYLGLR56Q\source\icu.net\BreakIterator.cs:line 386
   at Icu.BreakIterator.GetWordBoundaries(Locale locale, String text, Boolean includeSpacesAndPunctuation) in d:\JenkinsSlaveHome\slave2\workspace\icu-dotnet_master-XUIQATPXJBEMAPQAXECBOMRZFIJEQ5ACEARUZRESUNQWYLGLR56Q\source\icu.net\BreakIterator.cs:line 368
   at IcuAVE.AVETest.RunAVETest(CountdownEvent latch, String fileName) in f:\Users\Shad\documents\visual studio 2017\Projects\IcuAVE\IcuAVE\AVETest.cs:line 50
   at IcuAVE.AVETest.<>c__DisplayClass0_0.<TestAccessViolationException>b__0() in f:\Users\Shad\documents\visual studio 2017\Projects\IcuAVE\IcuAVE\AVETest.cs:line 35
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
   at Icu.NativeMethods.ubrk_next(IntPtr bi) in d:\JenkinsSlaveHome\slave2\workspace\icu-dotnet_master-XUIQATPXJBEMAPQAXECBOMRZFIJEQ5ACEARUZRESUNQWYLGLR56Q\source\icu.net\NativeMethods.cs:line 1732
   at Icu.RuleBasedBreakIterator.SetText(String text) in d:\JenkinsSlaveHome\slave2\workspace\icu-dotnet_master-XUIQATPXJBEMAPQAXECBOMRZFIJEQ5ACEARUZRESUNQWYLGLR56Q\source\icu.net\RuleBasedBreakIterator.cs:line 377
   at Icu.BreakIterator.GetBoundaries(UBreakIteratorType type, Locale locale, String text, Boolean includeSpacesAndPunctuation) in d:\JenkinsSlaveHome\slave2\workspace\icu-dotnet_master-XUIQATPXJBEMAPQAXECBOMRZFIJEQ5ACEARUZRESUNQWYLGLR56Q\source\icu.net\BreakIterator.cs:line 386
   at Icu.BreakIterator.GetWordBoundaries(Locale locale, String text, Boolean includeSpacesAndPunctuation) in d:\JenkinsSlaveHome\slave2\workspace\icu-dotnet_master-XUIQATPXJBEMAPQAXECBOMRZFIJEQ5ACEARUZRESUNQWYLGLR56Q\source\icu.net\BreakIterator.cs:line 368
   at IcuAVE.AVETest.RunAVETest(CountdownEvent latch, String fileName) in f:\Users\Shad\documents\visual studio 2017\Projects\IcuAVE\IcuAVE\AVETest.cs:line 50
   at IcuAVE.AVETest.<>c__DisplayClass0_0.<TestAccessViolationException>b__0() in f:\Users\Shad\documents\visual studio 2017\Projects\IcuAVE\IcuAVE\AVETest.cs:line 35
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

## Steps to Reproduce

1. Clone the repository from https://github.com/NightOwl888/IcuAVE
2. Open in Visual Studio and build the solution
3. Under Visual Studio's Test Explorer right click the `IcuAVE.NUnit.TestAccessViolationException` test and choose "Run Selected Tests"
4. Navigate to the Output pane and choose "Tests" from the "Show output from" dropdown, and check for the stack trace of the `AccessViolationException`
5. If the error didn't happen the first time, try again - it doesn't occur 100% of the time the test is run. 

> **NOTE:** The test never actually fails in .NET Framework, but this exception causes a fatal crash of the NUnit test runner when running under .NET Core (when merging updates from #37).

![image](https://user-images.githubusercontent.com/1538288/31863928-1e013e46-b77f-11e7-94b7-5576be59bc9d.png)

**Comment by jnm2** [comment]
The crash is in NativeMethods.cs. The first thing I'd look for is  p/invoke definition that uses `int` instead of `IntPtr` or something like that, if there is any chance that the process is running under a different bitness under .NET Core.

**Comment by jnm2** [comment]
I've run IcuAVE.NUnit.TestAccessViolationException 10 times back to back on my machine with and didn't get an exception. I have VS 15.4.0, NUnit adapter 3.8.0, .NET Framework 4.7.1. Do you have a complete repro?

**Comment by NightOwl888** [comment]
Did you check the Output tab? The exception is not actually caught by anything and the test still passes. You might also try playing with the number of threads, number of iterations, adding a [Repeat(20)] attribute, etc. 

My environment:

Windows 10 Pro
VS 15.4.1
NUnit3TestAdapter 3.8.0 (installed via NuGet)
.NET Framework 4.6.1
4th Generation Intel i7 Quad-core

We have a "more complete repro", but there is a ton of infrastructure built around the test so I thought I would do you a favor and give you a more isolated test case. There are 2 tests that randomly throw these exceptions [TestThaiAnalyzer.TestRandomStrings](https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Tests.Analysis.Common/Analysis/Th/TestThaiAnalyzer.cs#L139) and [TestThaiAnalyzer.TestRandomHugeStrings](https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Tests.Analysis.Common/Analysis/Th/TestThaiAnalyzer.cs#L155). Note that if you clone locally, the tests are added as linked files to the [src/dotnet/Lucene.Net.Tests.ICU](https://github.com/apache/lucenenet/tree/master/src/dotnet/Lucene.Net.Tests.ICU) project, which is where it is run from.

We are using a rather old version of icu.net that has support for .NET Standard 1.5 that isn't the same as the current production version. But I have tested it with the latest fixes, and it still throws the AVE.

Also, I have confirmed it fails on our CI server and another developer mentioned he was seeing it as well.

**Comment by jnm2** [comment]
My bad, I misunderstood the 'note' section to be saying I'd have to change the project in order to see it. Let me look for that.

**Comment by NightOwl888** [comment]
No problem.

Note that we are also seeing other bad behavior from the same tests:

1. Failures on some random strings: https://teamcity.jetbrains.com/viewLog.html?buildId=1203344&tab=buildResultsDiv&buildTypeId=LuceneNet_PortableBuilds_TestOnNet451
2. The tests occasionally run forever unless constrained with a timeout

I suspect all of these issues are concurrency related.

**Comment by jnm2** [comment]
Not able to get it to happen on VS 15.4.1, windows 10.0.16299.19. Test passes, output window shows no AVE.

**Comment by NightOwl888** [comment]
Are you running under x86 or x64? I just noticed the failure happens much more frequently on x64. See number 2 [here](https://msdn.microsoft.com/en-us/library/ee782531.aspx).

**Comment by jnm2** [comment]
Indeed, switching to x64 repro'd the AVE on the first try.

The AVE repros in the NUnit test, and the xUnit test and the console app (once you add `<Prefer32Bit>false</Prefer32Bit>` to the project).

Is the question why AVE is fatal on NUnit on .NET Core?

**Comment by NightOwl888** [comment]
> Is the question why AVE is fatal on NUnit on .NET Core?

No, I already went over that with the NUnit team/Microsoft [here](https://github.com/nunit/dotnet-test-nunit/issues/115). This one is about reporting this bug, which has been plaguing our project for about a year now. I am hoping we can get icu.net patched.

**Comment by NightOwl888** [comment]
So, I guess that rules out NUnit. We've also ruled out Lucene.Net. So, the problem must be in icu.net.

**Comment by jnm2** [comment]
Is there anything left I can help answer for https://github.com/nunit/dotnet-test-nunit/issues/115 or should it be closed?

**Comment by NightOwl888** [comment]
That should remain open as well. We need a fix for the test runner so AVE doesn't crash fatally. That will take some effort from the .NET Core team to get done.

**Comment by NightOwl888** [comment]
The console app has a different stack trace 

```
   at Icu.RuleBasedBreakIterator.SetText(String text) in d:\JenkinsSlaveHome\slave2\workspace\icu-dotnet_master-XUIQATPXJBEMAPQAXECBOMRZFIJEQ5ACEARUZRESUNQWYLGLR56Q\source\icu.net\RuleBasedBreakIterator.cs:line 418
   at Icu.BreakIterator.GetBoundaries(UBreakIteratorType type, Locale locale, String text, Boolean includeSpacesAndPunctuation) in d:\JenkinsSlaveHome\slave2\workspace\icu-dotnet_master-XUIQATPXJBEMAPQAXECBOMRZFIJEQ5ACEARUZRESUNQWYLGLR56Q\source\icu.net\BreakIterator.cs:line 388
   at IcuAVE.Test.RunAVETest(CountdownEvent latch, String fileName) in f:\Users\Shad\documents\visual studio 2017\Projects\IcuAVE\IcuAVE\Test.cs:line 63
   at IcuAVE.Test.<>c__DisplayClass0_0.<RunTest>b__0() in f:\Users\Shad\documents\visual studio 2017\Projects\IcuAVE\IcuAVE\Test.cs:line 32
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by jnm2** [comment]
> We need a fix for the test runner so AVE doesn't crash fatally. 

From reading the issue it looked like there's nothing NUnit *can* do to stop `dotnet.exe` from crashing. Is that not the case?

**Comment by NightOwl888** [comment]
If .NET Core brings back the [features to handle AccessViolationException](https://stackoverflow.com/a/4759831/181087), then NUnit will be able to prevent the test runner from crashing.

**Comment by NightOwl888** [comment]
It looks like `RuleBasedBreakIterator` isn't thread safe. The way break iterators are used in the JDK is to cache a singleton instance of each of the types and then clone the instance to get a new one. So you would call `.getInstance()` followed by `.clone()`. It looks like the [ubrk_safeClone](http://www.icu-project.org/apiref/icu4c/ubrk_8h.html#a6901f59d9c74bc8e16b9994cb1be7679) isn't being used, which is probably the main issue.

**Comment by NightOwl888** [comment]
Never mind, `ubrk_safeClone` has been deprecated. Need to look into this more.

**Comment by ermshiperete** [comment]
I wonder if this is related to #54 and the workaround implemented there (in icu.net 2.3.0-beta0008) would help here as well? @NightOwl888 could you try with that version and calling `Wrapper.Init()` at the beginning of the test?

**Comment by NightOwl888** [comment]
@ermshiperete 

I tried with that fix already and get the same result. As previously mentioned, I believe the reason for this is because without using `ubrk_safeClone` on the instance you get from `ubrk_open`, you get the same BreakIterator instance (if the break iterator type and  locale are the same) for every thread and when 2 threads both execute at the same time on the same instance there is a possibility they will attempt to allocate the same memory location.

Have a look at [this example](https://github.com/apache/lucene-solr/blob/master/lucene/analysis/common/src/java/org/apache/lucene/analysis/th/ThaiTokenizer.java). It first allocates a [static `sentenceProto` variable](https://github.com/apache/lucene-solr/blob/master/lucene/analysis/common/src/java/org/apache/lucene/analysis/th/ThaiTokenizer.java#L50) by calling `BreakIterator.getWordInstance()`, then it calls [`sentenceProto.clone()`](https://github.com/apache/lucene-solr/blob/master/lucene/analysis/common/src/java/org/apache/lucene/analysis/th/ThaiTokenizer.java#L68) for each instance of `ThaiTokenizer` that is created.

Every usage example of BreakIterator I have seen (whether it is the JDK BreakIterator or ICU4J) uses this same pattern.

This could "sort of" be fixed by implementing `ubrk_safeClone` and calling `return new RuleBasedBreakIterator(UBreakIteratorType.WORD, locale).Clone();` [here](`https://github.com/sillsdev/icu-dotnet/blob/master/source/icu.net/BreakIterator.cs#L286) (and for the other "Create" methods as well), but that creates a gap in functionality for anyone who wants to use the default instance for some reason. Unfortunately, the methods were named "Create" instead of "Get" even though under the covers the BreakIterator is cached and you get a pointer to the same instance (in C++ anyway) every time the method is called.

**Comment by ermshiperete** [comment]
@NightOwl888 PR #57 implements the Clone method.
